import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import SignUpDialog from "@/components/signup-dialog";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Sunshower Tech Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <SignUpDialog />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
